### ISSUE TITLE
json.decoder.JSONDecodeError: Extra data: line 1 column 1187 (char 1186)

### ISSUE THREAD

**Issue by dapor2000** [produnis/myscripts#1]
picture directory is /home/rss/onlysexygirls
/home/rss/onlysexygirls/0archive_posted.txt
Ready to post new picture: 125964794106.jpg
Looking for txt-file /home/rss/onlysexygirls/125964794106.txt

No txt-file found. Posting Image only

Upload pic 125964794106.jpg with path /home/rss/onlysexygirls/125964794106.jpg to Diaspora
Traceback (most recent call last):
  File "/home/rss/pic2diaspora.py", line 102, in <module>
    stream.post(photo=pics, text=textmessage, aspect_ids=aspect_to_post)
  File "/home/rss/.local/lib/python3.5/site-packages/diaspy/streams.py", line 262, in post
    if photo: data['photos'] = self._photoupload(photo)
  File "/home/rss/.local/lib/python3.5/site-packages/diaspy/streams.py", line 293, in _photoupload
    if not aspects: aspects = self._connection.getUserData()['aspects']
  File "/home/rss/.local/lib/python3.5/site-packages/diaspy/connection.py", line 226, in getUserData
    return json.loads(userdata)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 1187 (char 1186)

# python3 --version
Python 3.5.2

**Comment by produnis** [comment]
I had this error, too, and solved it by downloading `diaspy` directly from github and then do a manually pip3 install,
see here: https://github.com/marekjm/diaspy/issues/22
